app:
  config:
    keycloak:
      url: http://localhost:8181/auth
      realm: oauth_server

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          spring-cloud-gateway-client:
            provider: keycloak
            client-id: spring-cloud-gateway-client
            client-secret: gLup2zu874lvwEsPXLYWNB4FCEIIa7a7
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client
            scope: openid

      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs